"""add shipping line

Revision ID: 14ab10250349
Revises: b10b21c8e815
Create Date: 2026-06-03 05:38:14.039134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ab10250349'
down_revision: Union[str, None] = 'b10b21c8e815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key('fk_container_ccro_document', 'containers', 'documents', ['ccro_document_id'], ['id'], use_alter=True)
    op.add_column('shipments', sa.Column('shipping_line_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'shipping_lines', ['shipping_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'shipping_line_id')
    op.drop_constraint('fk_container_ccro_document', 'containers', type_='foreignkey')
    op.drop_table('shipping_lines')
    # ### end Alembic commands ###
