"""initial

Revision ID: b10b21c8e815
Revises: 
Create Date: 2026-06-03 04:31:10.974339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b10b21c8e815'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loading_ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('offloading_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rop_inspection_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trucks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=False),
    sa.Column('contractor', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('team', sa.Enum('CUSTOMER', 'FFD', 'PRO', 'TRANSPORT', 'DC', 'MANAGEMENT', name='team_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('team', sa.Enum('CUSTOMER', 'FFD', 'PRO', 'TRANSPORT', 'DC', 'MANAGEMENT', name='team_enum'), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bl_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.Enum('CUSTOMER', 'FFD_REVIEW', 'IN_PROGRESS', 'TRANSPORT', 'DC_TRANSPORT', 'COMPLETED', name='shipment_stage_enum'), nullable=False),
    sa.Column('pull_out_date', sa.Date(), nullable=True),
    sa.Column('product_type_id', sa.UUID(), nullable=True),
    sa.Column('loading_port_id', sa.UUID(), nullable=True),
    sa.Column('rop_inspection_type_id', sa.UUID(), nullable=True),
    sa.Column('offloading_point_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loading_port_id'], ['loading_ports.id'], ),
    sa.ForeignKeyConstraint(['offloading_point_id'], ['offloading_points.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.ForeignKeyConstraint(['rop_inspection_type_id'], ['rop_inspection_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_bl_number'), 'shipments', ['bl_number'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('container_number', sa.String(length=50), nullable=False),
    sa.Column('ccro_document_id', sa.UUID(), nullable=True),
    sa.Column('truck_id', sa.UUID(), nullable=True),
    sa.Column('expected_arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offloading_point_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'BREAKDOWN', 'AT_DC', 'OFFLOADED', 'RETURNED', name='container_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ccro_document_id'], ['documents.id'], name='fk_container_ccro_document', use_alter=True),
    sa.ForeignKeyConstraint(['offloading_point_id'], ['offloading_points.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('shipment_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('PERMIT', 'BAYAN', 'DO', 'CCRO', 'CCRO_ROP', name='task_type_enum'), nullable=False),
    sa.Column('assigned_team', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'ON_HOLD', 'COMPLETED', name='task_status_enum'), nullable=False),
    sa.Column('hold_entity', sa.Enum('SHIPPING_LINE', 'ROP', 'MOAF', 'PORT', name='external_entity_enum'), nullable=True),
    sa.Column('hold_reason', sa.Enum('SL_DO_NOT_SENT', 'SL_DO_EXPIRED_REVALIDATING', 'SL_MANIFEST_NOT_UPLOADED', 'SL_DOCUMENTATION_ISSUE', 'ROP_APPROVAL_PENDING', 'ROP_CCRO_ISSUE', 'MOAF_APPROVAL_PENDING', 'PORT_AWAITING_CCRO', 'PORT_REJECTED_ROP_ISSUE', 'PORT_REJECTED_SL_ISSUE', name='hold_reason_enum'), nullable=True),
    sa.Column('hold_remark', sa.Text(), nullable=True),
    sa.Column('release_remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Enum('COMMERCIAL_INVOICE', 'PACKING_LIST', 'CERT_OF_ORIGIN', 'HALAL_CERT', 'BL', 'HEALTH_CERT', 'PERMIT', 'BAYAN', 'DO', 'CCRO', name='doc_type_enum'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('oci_path', sa.String(length=1024), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=False),
    sa.Column('compressed_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['shipment_tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('SHIPMENT_CREATED', 'DOCUMENTS_SUBMITTED', 'DOCUMENTS_REJECTED', 'DOCUMENTS_APPROVED', 'TASK_CREATED', 'TASK_HOLD_ASSIGNED', 'TASK_HOLD_RELEASED', 'TASK_COMPLETED', 'STAGE_CHANGED', 'CONTAINER_ADDED', 'TRUCK_ASSIGNED', 'BREAKDOWN_REPORTED', 'CONTAINER_OFFLOADED', 'CONTAINER_RETURNED', 'SENT_BACK_TO_FFD', name='event_type_enum'), nullable=False),
    sa.Column('stage_from', sa.Enum('CUSTOMER', 'FFD_REVIEW', 'IN_PROGRESS', 'TRANSPORT', 'DC_TRANSPORT', 'COMPLETED', name='shipment_stage_enum'), nullable=True),
    sa.Column('stage_to', sa.Enum('CUSTOMER', 'FFD_REVIEW', 'IN_PROGRESS', 'TRANSPORT', 'DC_TRANSPORT', 'COMPLETED', name='shipment_stage_enum'), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['shipment_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('container_events')
    op.drop_table('shipment_tasks')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('containers')
    op.drop_index(op.f('ix_shipments_bl_number'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trucks')
    op.drop_table('rop_inspection_types')
    op.drop_table('product_types')
    op.drop_table('offloading_points')
    op.drop_table('loading_ports')
    # ### end Alembic commands ###
